// <auto-generated />
using System;
using System.Collections.Generic;
using Shreksoft.Bank.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Shreksoft.Bank.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BankDbContext))]
    partial class BankDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Shreksoft.Bank.Core.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Money", "Shreksoft.Bank.Core.Domain.Accounts.Account.Money#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "Shreksoft.Bank.Core.Domain.Accounts.Account.Money#Money.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<byte>("Scale")
                                        .HasColumnType("INTEGER");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Shreksoft.Bank.Core.Domain.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Info", "Shreksoft.Bank.Core.Domain.Clients.Client.Info#ClientInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Email")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("TEXT");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "BirthDate", "Shreksoft.Bank.Core.Domain.Clients.Client.Info#ClientInfo.BirthDate#BirthDate", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<DateOnly>("Date")
                                        .HasColumnType("TEXT");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "FullName", "Shreksoft.Bank.Core.Domain.Clients.Client.Info#ClientInfo.FullName#FullName", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("LastName")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("MiddleName")
                                        .HasColumnType("TEXT");
                                });
                        });

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Shreksoft.Bank.Core.Domain.Transfers.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Commission")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RecipientAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SenderAmount")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "RecipientSide", "Shreksoft.Bank.Core.Domain.Transfers.Transfer.RecipientSide#TransferSide", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("AccountId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ClientId")
                                .HasColumnType("TEXT");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "Shreksoft.Bank.Core.Domain.Transfers.Transfer.RecipientSide#TransferSide.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<byte>("Scale")
                                        .HasColumnType("INTEGER");
                                });
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SenderSide", "Shreksoft.Bank.Core.Domain.Transfers.Transfer.SenderSide#TransferSide", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("AccountId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ClientId")
                                .HasColumnType("TEXT");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "Shreksoft.Bank.Core.Domain.Transfers.Transfer.SenderSide#TransferSide.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<byte>("Scale")
                                        .HasColumnType("INTEGER");
                                });
                        });

                    b.HasKey("Id");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("Shreksoft.Bank.Core.Domain.Accounts.Account", b =>
                {
                    b.HasOne("Shreksoft.Bank.Core.Domain.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
