// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shreksoft.Bank.Infrastructure.Data;

#nullable disable

namespace Shreksoft.Bank.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BankDbContext))]
    partial class BankDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shreksoft.Bank.Core.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Money", "Shreksoft.Bank.Core.Domain.Accounts.Account.Money#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "Shreksoft.Bank.Core.Domain.Accounts.Account.Money#Money.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasColumnType("text");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Shreksoft.Bank.Core.Domain.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Info", "Shreksoft.Bank.Core.Domain.Clients.Client.Info#ClientInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("text");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "BirthDate", "Shreksoft.Bank.Core.Domain.Clients.Client.Info#ClientInfo.BirthDate#BirthDate", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<DateOnly>("Date")
                                        .HasColumnType("date");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "FullName", "Shreksoft.Bank.Core.Domain.Clients.Client.Info#ClientInfo.FullName#FullName", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("LastName")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("MiddleName")
                                        .HasColumnType("text");
                                });
                        });

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Shreksoft.Bank.Core.Domain.Transfers.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CommissionMoney", "Shreksoft.Bank.Core.Domain.Transfers.Transfer.CommissionMoney#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "Shreksoft.Bank.Core.Domain.Transfers.Transfer.CommissionMoney#Money.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasColumnType("text");
                                });
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "RecipientMoney", "Shreksoft.Bank.Core.Domain.Transfers.Transfer.RecipientMoney#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "Shreksoft.Bank.Core.Domain.Transfers.Transfer.RecipientMoney#Money.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasColumnType("text");
                                });
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "RecipientSide", "Shreksoft.Bank.Core.Domain.Transfers.Transfer.RecipientSide#TransferSide", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ClientId")
                                .HasColumnType("uuid");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SenderMoney", "Shreksoft.Bank.Core.Domain.Transfers.Transfer.SenderMoney#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "Shreksoft.Bank.Core.Domain.Transfers.Transfer.SenderMoney#Money.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasColumnType("text");
                                });
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SenderSide", "Shreksoft.Bank.Core.Domain.Transfers.Transfer.SenderSide#TransferSide", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ClientId")
                                .HasColumnType("uuid");
                        });

                    b.HasKey("Id");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("Shreksoft.Bank.Core.Domain.Accounts.Account", b =>
                {
                    b.HasOne("Shreksoft.Bank.Core.Domain.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
