// <auto-generated />
using System;
using System.Collections.Generic;
using CBS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CBS.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CbsContext))]
    partial class CbsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("CBS.Core.Accounts.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Money", "CBS.Core.Accounts.Domain.Account.Money#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("CBS.Core.Clients.Domain.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Info", "CBS.Core.Clients.Domain.Client.Info#ClientInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Email")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("TEXT");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "BirthDate", "CBS.Core.Clients.Domain.Client.Info#ClientInfo.BirthDate#BirthDate", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<DateOnly>("Date")
                                        .HasColumnType("TEXT");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "FullName", "CBS.Core.Clients.Domain.Client.Info#ClientInfo.FullName#FullName", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("LastName")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("MiddleName")
                                        .HasColumnType("TEXT");
                                });
                        });

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
