@Api_HostAddress = http://localhost:5294

###
# @name CreateClient
POST {{Api_HostAddress}}/api/clients/create
Content-Type: application/json

{
    "firstName": "Иван",
    "middleName": null,
    "lastName": "Петров",
    "birthDate": "1998-07-21",
    "email": "ivan@example.com",
    "phoneNumber": "+79991234567"
}

> {%


 client.global.set("clientId", response.body.id);


%}

###
GET {{Api_HostAddress}}/api/clients/{{clientId}}
Content-Type: application/json


###
POST {{Api_HostAddress}}/api/Account/create
Content-Type: application/json

{
    "clientId": "{{clientId}}",
    "currencyCode": 1
}

> {%


 client.global.set("accountId", response.body.id);


%}

###
GET {{Api_HostAddress}}/api/Account/{{accountId}}
Content-Type: application/json

###
POST {{Api_HostAddress}}/api/Account/Transfer
Content-Type: application/json

{
    "senderAccId": "71F23965-6ECD-4CB5-A612-48E95013E336",
    "recipientAccId": "536C34BE-AC17-4370-B735-7771B43CC0CC",
    "amount": 100
}


###
PUT {{Api_HostAddress}}/api/Account/Deposit
Content-Type: application/json

{
    "accountId": "{{accountId}}",
    "amount": 300
}
