<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shreksoft.Bank.Core\Shreksoft.Bank.Core.csproj"/>
        <ProjectReference Include="..\Shreksoft.Bank.Infrastructure\Data\Shreksoft.Bank.Infrastructure.Data.csproj"/>
        <ProjectReference Include="..\Shreksoft.Bank.Application\Shreksoft.Bank.Application.csproj"/>
    </ItemGroup>

</Project>
