@Api_HostAddress = http://localhost:5294

###
# @name CreateClient
POST {{Api_HostAddress}}/api/clients/create
Content-Type: application/json

{
    "firstName": "Иван",
    "middleName": null,
    "lastName": "Петров",
    "birthDate": "1998-07-21",
    "email": "ivan@example.com",
    "phoneNumber": "+79991234567"
}

> {%


 client.global.set("clientId", response.body.id);


%}

###
GET {{Api_HostAddress}}/api/clients/{{clientId}}
Content-Type: application/json


###
POST {{Api_HostAddress}}/api/Account/create
Content-Type: application/json

{
    "clientId": "{{clientId}}",
    "currencyCode": 2
}

> {%


 client.global.set("accountId", response.body.id);


%}

###
GET {{Api_HostAddress}}/api/Account/{{accountId}}
Content-Type: application/json

###
POST {{Api_HostAddress}}/api/Account/Transfer
Content-Type: application/json

{
    "senderAccId": "1757C04A-73FD-4169-8BFA-565BEB97BA82",
    "recipientAccId": "B9B669DD-24F4-48E0-AC93-1C4C6287F396",
    "amount": 100
}


###
PUT {{Api_HostAddress}}/api/Account/Deposit
Content-Type: application/json

{
    "accountId": "{{accountId}}",
    "amount": 300.11122
}
