@Api_HostAddress = http://localhost:5294

###
# @name CreateClient
POST {{Api_HostAddress}}/api/clients/create
Content-Type: application/json

{
  "firstName": "Иван",
  "middleName": null,
  "lastName": "Петров",
  "birthDate": "1998-07-21",
  "email": "ivan@example.com",
  "phoneNumber": "+79991234567"
}

> {%
 client.global.set("clientId", response.body.id);
%}

###
GET {{Api_HostAddress}}/api/clients/{{clientId}}
Content-Type: application/json


###
POST {{Api_HostAddress}}/api/Account/create
Content-Type: application/json

{
  "clientId": "{{clientId}}",
  "currencyCode": 2
}

> {%
 client.global.set("accountId", response.body.id);
%}

###
GET {{Api_HostAddress}}/api/Account/{{accountId}}
Content-Type: application/json

###
POST {{Api_HostAddress}}/api/Account/Transfer
Content-Type: application/json

{
  "senderAccId": "6FEC9270-C6C3-4259-9125-59937DC7DB3A",
  "recipientAccId": "3476F5FA-25E2-4418-A2B2-FAB0FFB16544",
  "amount": 90.000016
}


###
PUT {{Api_HostAddress}}/api/Account/Deposit
Content-Type: application/json

{
  "accountId": "{{accountId}}",
  "amount": 100.227
}
